# /opt/architect_configs/group_vars/all.yml
---
# Variables applicable to all hosts

# System settings
system_timezone: "America/Denver"

# User management
admin_users:
  - username: aiseed
    shell: /bin/bash
  - username: pong
    shell: /bin/bash

# Package management
common_packages_to_install:
  - vim
  - tmux
  - curl
  - wget
  - htop
  - ncdu
  - tree
  - unzip
  - net-tools
  - dnsutils
  - apt-transport-https
  - ca-certificates
  - gnupg
  - python3-pip
  - python3-venv
  - chrony # Ensure chrony is listed here now

# --- Variables for Security Role ---
security_ssh_port: 22
security_fail2ban_enabled: true
# Define ignoreip here, assuming local subnet is generally trusted for fail2ban
# Review this subnet if your local network differs from 192.168.0.x
fail2ban_ignoreip: '127.0.0.1/8 ::1 192.168.0.0/24'

# Variables for Docker Role
docker_users_to_group:
  - aiseed
  - pong

