# /opt/architect_configs/group_vars/all.yml
---
# Variables applicable to all hosts

# System settings
system_timezone: "America/Denver"

# User management
admin_users:
  - username: aiseed
    shell: /bin/bash
  - username: pong
    shell: /bin/bash

# --- Package Management --- (Simplified Definition)
baseline_system_packages:
  - vim
  - tmux
  - curl
  - wget
  - htop
  - ncdu
  - tree
  - unzip
  - net-tools
  - dnsutils
  - apt-transport-https
  - ca-certificates
  - gnupg
  - python3-pip
  - python3-venv

# --- Variables for Security Role ---
security_ssh_port: 22
security_fail2ban_enabled: true
fail2ban_ignoreip: '127.0.0.1/8 ::1 192.168.0.0/24' # Review subnet if needed

# --- Variables for Docker Role ---
docker_users_to_group:
  - aiseed
  - pong

# --- Variables for Promtail Role ---
loki_server_url: "http://192.168.0.95:3100/loki/api/v1/push"

# --- Variables potentially used by Security Role UFW tasks ---
monitoring_allowed_sources: '192.168.0.0/24' # Review subnet if needed

