# /opt/architect_configs/group_vars/all.yml
---
# Variables applicable to all hosts

# System settings
system_timezone: "America/Denver"

# User management
admin_users:
  - username: aiseed
    shell: /bin/bash
  - username: pong
    shell: /bin/bash

# --- Package Management ---
common_packages_to_install:
  - vim
  - tmux
  - curl
  - wget
  - htop
  - ncdu
  - tree
  - unzip
  - net-tools            # Provides ifconfig, netstat etc.
  - dnsutils             # Provides dig, nslookup
  - apt-transport-https # Often needed for custom apt repos
  - ca-certificates     # Ensure up-to-date certs
  - gnupg                # Often needed for adding repo keys
  - python3-pip          # Useful Python package installer
  - python3-venv         # For creating Python virtual environments
  # Note: chrony is installed via dedicated task in common role

# --- Variables for Security Role ---
security_ssh_port: 22
security_fail2ban_enabled: true
fail2ban_ignoreip: '127.0.0.1/8 ::1 192.168.0.0/24' # Review subnet if needed

# --- Variables for Docker Role ---
docker_users_to_group:
  - aiseed
  - pong

# --- Variables for Promtail Role ---
loki_server_url: "http://192.168.0.95:3100/loki/api/v1/push"

# --- Variables potentially used by Security Role UFW tasks ---
# (Specific rules defined in server.yml/clients.yml take precedence)
monitoring_allowed_sources: '192.168.0.0/24' # Review subnet if needed

