---
# Ansible Collection Requirements
collections:
  - name: community.general
    version: ">=9.1.0,<11.0.0" # Specify a reasonable version range
  - name: community.docker
    version: ">=3.4.0,<5.0.0" # Specify a reasonable version range
  # Add other collections here if roles require them
