# /opt/architect_configs/site.yml
# Version 1.6 (Automated) - Corrected prometheus var name, vars in plays
---
- name: Apply common configuration to all hosts
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    # Define common vars needed by roles in this play directly here
    system_timezone: "America/Denver"
    admin_users:
      - { username: aiseed, shell: /bin/bash }
      - { username: pong, shell: /bin/bash }
    common_pkgs:
      - build-essential
      - python3-dev
      - curl
      - wget
      - git
      - vim
      - tmux
      - htop
      - net-tools
      - dnsutils
      - unzip
      - ca-certificates
      - gnupg
      - python3-pip
      - python3-venv
    security_ssh_port: 22
    security_fail2ban_enabled: false
    fail2ban_ignoreip: '127.0.0.1/8 ::1 192.168.0.0/24'
    docker_users_to_group:
      - aiseed
      - pong
    monitoring_allowed_sources: '192.168.0.0/24'
    node_exporter_port: 9100
    loki_server_url: "http://192.168.0.95:3100/loki/api/v1/push"
    prometheus_port: 9091 # <<< Define standard port var globally if needed by multiple plays/roles
    server_ufw_allow_rules:
      - { comment: "Allow SSH from Client 'pong@pop-os'", port: '{{ security_ssh_port | default(22) }}', proto: tcp, rule: allow, src: '192.168.0.96' }
      - { comment: "Allow SSH from Localhost", port: '{{ security_ssh_port | default(22) }}', proto: tcp, rule: allow, src: '127.0.0.1' }
      # Use correct var name 'prometheus_port' here too:
      - { comment: "Allow Prometheus from Client Subnet", port: '{{ prometheus_port | default(9091) }}', proto: tcp, rule: allow, src: '{{ monitoring_allowed_sources }}' }
      - { comment: "Allow Loki from Client Subnet", port: 3100, proto: tcp, rule: allow, src: '{{ monitoring_allowed_sources }}' }
    client_ufw_allow_rules:
      - { comment: "Allow SSH from Server 'aiseed@thosedataguys-s'", port: '{{ security_ssh_port | default(22) }}', proto: tcp, rule: allow, src: '192.168.0.95' }
      - { comment: "Allow SSH from Localhost", port: '{{ security_ssh_port | default(22) }}', proto: tcp, rule: allow, src: '127.0.0.1' }
  roles:
    - common
    - security
    - docker
    - node_exporter
    - promtail

# --- Server-Specific Configuration ---
- name: Configure server-specific settings
  hosts: server
  become: yes
  gather_facts: no
  vars:
    # Define ALL variables needed by server roles HERE
    prometheus_port: 9091 # <<< CORRECTED NAME HERE
    prometheus_config_dir: "/opt/docker/prometheus/config"
    prometheus_data_dir: "/opt/docker/prometheus/data"
    prometheus_compose_dir: "/opt/docker/prometheus"
    docker_run_user: "aiseed"
    docker_run_group: "aiseed"
    prometheus_template_name: "docker-compose.yml.j2"
    prometheus_compose_file_path: "{{ prometheus_compose_dir }}/docker-compose.yml"
    prometheus_config_template: "prometheus.yml.j2"
    prometheus_config_file_path: "{{ prometheus_config_dir }}/prometheus.yml"
    # Loki vars
    loki_config_dir: "/opt/docker/loki/config"
    loki_data_dir: "/opt/docker/loki/data"
    loki_port: 3100
    loki_compose_file_path: "{{ prometheus_compose_dir | replace('prometheus','loki') }}/docker-compose.yml"
  roles:
    - prometheus
    - loki
    # - grafana

# --- Client-Specific Configuration ---
- name: Configure client-specific settings
  hosts: clients
  become: yes
  gather_facts: no
  vars:
    placeholder_client_var: true
  roles:
    - prompt_debug
