# /opt/architect_configs/site.yml
---
- name: Apply common configuration to all hosts
  hosts: all # Targets both [server] and [clients] groups
  become: yes
  gather_facts: yes # Gather facts once for all hosts here
  vars_files: # <<< ADDED THIS SECTION
    - ../inventory/group_vars/all.yml # <<< Path relative to this playbook (site.yml)
  # Define variables directly here as workaround for group_vars/all.yml issue - NOTE: Keeping existing vars block
  vars:
    system_timezone: "America/Denver"
    admin_users:
      - { username: aiseed, shell: /bin/bash }
      - { username: pong, shell: /bin/bash }
    baseline_system_packages: # Note: common_packages_to_install should come from all.yml now
      - vim
      - tmux
      - curl
      - wget
      - htop
      - ncdu
      - tree
      - unzip
      - net-tools
      - dnsutils
      - apt-transport-https
      - ca-certificates
      - gnupg
      - python3-pip
      - python3-venv
    security_ssh_port: 22
    security_fail2ban_enabled: true # Still skipped - investigate later
    fail2ban_ignoreip: '127.0.0.1/8 ::1 192.168.0.0/24'
    docker_users_to_group:
      - aiseed
      - pong
    loki_server_url: "http://192.168.0.95:3100/loki/api/v1/push"
    monitoring_allowed_sources: '192.168.0.0/24'
  roles:
    - common

- name: Apply security baseline to all hosts
  hosts: all
  become: yes
  gather_facts: no # Facts gathered already in first play
  roles:
    - security

- name: Configure Docker on all hosts
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - docker

- name: Configure Node Exporter on all hosts
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - node_exporter

- name: Configure Promtail on all hosts
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - promtail

# --- Server-Specific Configuration ---
- name: Configure server-specific settings
  hosts: server # TARGETS ONLY SERVER GROUP
  become: yes
  gather_facts: no
  roles:
    - prometheus # Prometheus role ONLY here
    - loki
    # - loki # Add Loki role here later - This was commented out in user provided file
    # - grafana # Add Grafana role here later - This was commented out

# --- Client-Specific Configuration ---
- name: Configure client-specific settings
  hosts: clients # TARGETS ONLY CLIENT GROUP
  become: yes
  gather_facts: no
  roles:
    # Add client-specific roles here later
    # - role: some_desktop_app # Example
    - prompt_debug # Keeping placeholder from user provided file
