---
# File: roles/prometheus/tasks/main.yml
# Version: Merged Local Fixes + Remote Volume Permission Fix

- name: Ensure Prometheus directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root # Let root create dirs initially
    group: root
    mode: '0755'
  loop:
    - "{{ prometheus_compose_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"
    # - "{{ role_path }}/templates" # REMOVED incorrect path
  become: yes
  tags: [prometheus, config]

- name: Deploy Prometheus configuration file (prometheus.yml)
  ansible.builtin.template:
    src: "{{ prometheus_config_template }}"
    dest: "{{ prometheus_config_file_path }}"
    owner: root # Config needs to be readable by container user
    group: root # Group read often sufficient
    mode: '0644'
  become: true
  # notify: Restart Prometheus container # Add if handler needed for config changes
  tags: [prometheus, config]

- name: Ensure Docker Compose V2 is available
  ansible.builtin.command: docker compose version
  register: compose_version_check
  changed_when: false
  failed_when: compose_version_check.rc != 0
  become: true # May need sudo if docker requires it
  tags: [prometheus, docker, config]

- name: Deploy Prometheus docker-compose.yml file from template
  # Places the file on host for inspection/manual use if needed
  ansible.builtin.template:
    src: "{{ prometheus_template_name }}"
    dest: "{{ prometheus_compose_file_path }}"
    owner: root # Root manages the compose definition
    group: root
    mode: '0644'
  become: true
  # notify: Restart Prometheus container # Add if handler needed for compose changes
  tags: [prometheus, config]

# --- BEGIN VOLUME PERMISSION FIX (from Remote) ---
- name: Ensure Prometheus data directory has correct permissions for container user
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "65534" # UID for nobody (adjust if Prometheus container uses different UID)
    group: "65534" # GID for nogroup (adjust if Prometheus container uses different GID)
    mode: '0775' # Writable by owner/group
  become: true
  tags: [prometheus, config, permissions]
# --- END VOLUME PERMISSION FIX ---

- name: Ensure potentially conflicting container is absent (Local Fix Re-applied)
  # Removes container with the explicit name if it exists from prior runs
  community.docker.docker_container:
    name: prometheus
    state: absent
    force_kill: yes
  become: yes
  ignore_errors: yes
  tags: [prometheus, docker, run]

- name: Ensure Prometheus container is running via Docker Compose (Local Fix Re-applied)
  # Uses definition directly for cleaner execution + correct parameters
  community.docker.docker_compose_v2:
    project_name: prometheus_stack # ADDED
    definition: "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}" # ADDED (switched from project_src)
    state: present
    pull: missing
  become: yes
  register: compose_result
  # notify: Restart Prometheus container # Add if handler needed
  tags: [prometheus, docker, run]
