---
# Tasks for Prometheus role - v1.1 Added Template Check
- name: Set Prometheus configuration facts
  ansible.builtin.set_fact:
    prometheus_config_dir: "/opt/docker/prometheus/config"
    prometheus_data_dir: "/opt/docker/prometheus/data"
    prometheus_compose_dir: "/opt/docker/prometheus"
    prometheus_port: "{{ prometheus_port_override | default(9090) }}"
    # Add other facts as needed

- name: Ensure Prometheus directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_run_user | default('root') }}" # Needs variable for user running docker/compose
    group: "{{ docker_run_group | default('root') }}"
    mode: '0755'
  loop:
    - "{{ prometheus_compose_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Deploy Prometheus configuration file from template (prometheus.yml)
  ansible.builtin.template:
    src: prometheus.yml.j2 # Assumes this template exists
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ docker_run_user | default('root') }}"
    group: "{{ docker_run_group | default('root') }}"
    mode: '0644'
  notify: Restart Prometheus container # Assumes handler exists

- name: Ensure Docker Compose V2 is available
  ansible.builtin.command: docker compose version
  register: compose_version_check
  changed_when: false
  failed_when: compose_version_check.rc != 0

# --- BEGIN TEMPLATE CHECK ---
- name: Check if Prometheus docker-compose template exists
  ansible.builtin.stat:
    path: "{{ PROMETHEUS_TEMPLATE_PATH }}" # Uses variable defined below for clarity
  vars:
    PROMETHEUS_TEMPLATE_PATH: "templates/docker-compose.yml.j2" # Path relative to ROLE root
  register: prometheus_template_stat

- name: Fail if Prometheus docker-compose template is missing
  ansible.builtin.fail:
    msg: |
      Required Prometheus template file not found!
      Path expected relative to role: '{{ PROMETHEUS_TEMPLATE_PATH }}'
      (Full path expected: '{{ role_path }}/{{ PROMETHEUS_TEMPLATE_PATH }}')
      Please create this file with the correct docker-compose content in the
      '{{ role_path }}/templates/' directory within the Git repository.
  when: not prometheus_template_stat.stat.exists
# --- END TEMPLATE CHECK ---

- name: Deploy Prometheus docker-compose.yml file from template
  ansible.builtin.template:
    src: docker-compose.yml.j2 # This path is now verified to exist by the task above
    dest: "{{ prometheus_compose_dir }}/docker-compose.yml"
    owner: "{{ docker_run_user | default('root') }}"
    group: "{{ docker_run_group | default('root') }}"
    mode: '0644'
  notify: Restart Prometheus container

# Add tasks to manage container (docker compose up -d) etc.
# ...

