# File: roles/prometheus/tasks/main.yml
# Version: Final Cleaned

- name: Ensure Prometheus directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_run_user | default('root') }}"
    group: "{{ docker_run_group | default('root') }}"
    mode: '0755'
  loop:
    - "{{ prometheus_compose_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"
  tags: [prometheus, config]

- name: Deploy Prometheus configuration file (prometheus.yml)
  ansible.builtin.template:
    src: "{{ prometheus_config_template }}"
    dest: "{{ prometheus_config_file_path }}"
    owner: "{{ docker_run_user | default('root') }}"
    group: "{{ docker_run_group | default('root') }}"
    mode: '0644'
  # notify: Restart Prometheus container # Add if handler needed for config changes
  tags: [prometheus, config]

- name: Ensure Docker Compose V2 is available
  ansible.builtin.command: docker compose version
  register: compose_version_check
  changed_when: false
  failed_when: compose_version_check.rc != 0
  tags: [prometheus, docker, config]

- name: Deploy Prometheus docker-compose.yml file from template
  # Places the file on host for inspection/manual use if needed
  ansible.builtin.template:
    src: "{{ prometheus_template_name }}"
    dest: "{{ prometheus_compose_file_path }}"
    owner: "{{ docker_run_user | default('root') }}"
    group: "{{ docker_run_group | default('root') }}"
    mode: '0644'
  # notify: Restart Prometheus container # Add if handler needed for compose changes
  tags: [prometheus, config]

- name: Ensure potentially conflicting container is absent
  # Removes container with the explicit name if it exists from prior runs
  community.docker.docker_container:
    name: prometheus
    state: absent
    force_kill: yes
  become: yes
  ignore_errors: yes
  tags: [prometheus, docker, run]

- name: Ensure Prometheus container is running via Docker Compose
  # Uses definition directly for cleaner execution
  community.docker.docker_compose_v2:
    project_name: prometheus_stack
    definition: "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
    pull: missing
  register: compose_result
  # notify: Restart Prometheus container # Add if handler needed
  tags: [prometheus, docker, run]
