# /opt/architect_configs/roles/common/tasks/main.yml
---
# Tasks applied to all hosts for common baseline configuration

- name: Update apt cache if older than 1 hour
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Only update if cache is > 1 hour old
  changed_when: false # Prevent this task alone from reporting 'changed' status
  tags: [common, packages]

- name: Install common packages defined in group_vars/all.yml
  ansible.builtin.apt:
    name: "{{ common_packages_to_install }}" # Uses the variable list
    state: present
  tags: [common, packages]

- name: Set system timezone
  community.general.timezone:
    name: "{{ system_timezone }}" # Uses the variable
  tags: [common, system]

# This is a basic user check; more robust management (groups, keys) needed for production
- name: Ensure admin users exist with correct shell
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    state: present
    # append: yes # Use if adding users to supplementary groups
    # groups: sudo # Example: ensure they are in sudo group
  loop: "{{ admin_users }}" # Loop through the list defined in group_vars/all.yml
  tags: [common, users]

# Add other common tasks here:
# - Configure NTP client (e.g., systemd-timesyncd or chrony)
# - Apply basic sysctl kernel parameters
# - Manage MOTD

