# /opt/architect_configs/roles/common/tasks/main.yml
---
# Tasks applied to all hosts for common baseline configuration

- name: Update apt cache if older than 1 hour
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Only update if cache is > 1 hour old
  changed_when: false # Prevent this task alone from reporting 'changed' status
  tags: [common, packages, apt]

- name: Install common packages defined in group_vars/all.yml
  ansible.builtin.apt:
    name: "{{ common_packages_to_install }}" # Uses variable list from group_vars/all.yml
    state: present
  tags: [common, packages, apt]

- name: Set system timezone
  community.general.timezone:
    name: "{{ system_timezone }}" # Uses variable from group_vars/all.yml
  tags: [common, system, timezone]

- name: Ensure systemd-timesyncd is active and enabled for time sync
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: yes
  tags: [common, system, ntp]

# Basic user check - ensures specified users exist with correct shell
# Note: Does not manage passwords or detailed group memberships here.
- name: Ensure admin users exist
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    state: present
  loop: "{{ admin_users }}" # Loop through list defined in group_vars/all.yml
  tags: [common, users]

# Add other common tasks below as needed:
# - Basic sysctl tuning (e.g., using ansible.posix.sysctl)
# - Managing MOTD (e.g., using ansible.builtin.template)
# - Ensuring specific directories exist

