# /opt/architect_configs/roles/docker/tasks/main.yml
---
# Tasks for installing and configuring Docker CE

- name: Ensure prerequisites for Docker repo are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  tags: [docker, packages]

# Remove conflicting docker.io package if present (best effort)
- name: Ensure conflicting docker.io package is removed
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose # Older compose
      - podman-docker # Conflicting package
      - containerd
      - runc
    state: absent
  ignore_errors: yes # Ignore if packages are not installed
  tags: [docker, packages]

- name: Ensure Docker apt key directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: [docker, repo]

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true # Overwrite if exists, ensures latest key
  tags: [docker, repo]

- name: Add Docker's official APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker # Creates /etc/apt/sources.list.d/docker.list
    update_cache: yes
  tags: [docker, repo]

- name: Install Docker CE packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io # Required by docker-ce
      - docker-buildx-plugin
      - docker-compose-plugin # Installs 'docker compose' command
    state: present
  tags: [docker, packages]
  notify: Restart docker # Handler needed

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  tags: [docker, users]

- name: Add specified users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes # Add to existing groups
  loop: "{{ docker_users_to_group | default([]) }}" # Use variable from group_vars/all.yml
  tags: [docker, users]

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  tags: [docker, service]

