---
# Handlers for Prometheus role

- name: Restart Prometheus container
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_compose_dir }}" # Use var defined in group_vars/server.yml
    state: present
    restarted: true

- name: Start Prometheus container
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_compose_dir }}" # Use var defined in group_vars/server.yml
    state: present
    started: true
