---
# Handlers for Prometheus role

- name: Restart Prometheus container
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_compose_dir }}" # Use var defined in tasks/main.yml
    state: present
    restarted: true # Use restarted instead of toggling started/stopped

- name: Start Prometheus container
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_compose_dir }}"
    state: present
    started: true

