name: Ansible CI - Lint and Syntax Check

# Run on pushes and pull requests targeting the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-syntax:
    name: Lint and Syntax Check
    runs-on: ubuntu-latest # Use standard GitHub Actions runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or '3.12' to match server more closely

      - name: Install Ansible Core, Lint, Yamllint
        run: |
          python -m pip install --upgrade pip
          # Install recent versions
          pip install ansible-core~=2.18.0 ansible-lint~=6.22 yamllint~=1.35
          echo "--- VERSIONS IN CI ---"
          ansible --version | head -n 1
          ansible-lint --version
          yamllint --version
          echo "--- END VERSIONS ---"

      # Consider adding collection install if lint rules require them
      # - name: Install Ansible Collections from file
      #   run: ansible-galaxy collection install -r collections/requirements.yml # Assumes file exists

      - name: Run yamllint (Strict)
        # Checks all YAML files for syntax and basic style issues
        run: yamllint . --strict

      - name: Run ansible-lint
        # Checks playbooks/roles for best practices and potential errors
        # Configure rules via .ansible-lint file in repo root later
        run: ansible-lint

      - name: Run ansible-playbook syntax-check
        # Checks if the main playbook can be parsed correctly by Ansible
        # Assumes inventory exists at this path relative to repo root
        run: ansible-playbook -i inventory/hosts_generated site.yml --syntax-check

